version: '3'

services:

  # Backend service configuration
  backend:
    build:
      context: .
    ports:
      - "5000:5000"
    environment:
      # Variables
      MYSQL_HOST: mysql 
      MYSQL_USER: root
      MYSQL_PASSWORD: root_password
      MYSQL_DB: tech_stack_db
    depends_on:
      - mysql

  # MySQL database service configuration
  mysql:
    image: mysql:5.7
    environment:
      # Variables
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: tech_stack_db
      MYSQL_USER: user_name
      MYSQL_PASSWORD: user_password
    volumes:
      - mysql-data:/var/lib/mysql

# Declaring a named volume
volumes:
  mysql-data:
